import {safeContentValidationError} from '../contracts/content-validation-error.js';
import {untrustedDataMessage} from '../../../security/src/prompt-policy.js';
import type {AIRequest} from '../provider.js';
export const CORRECTION_INSTRUCTIONS='Create a new ContentPlan from the original DATA and groundingFacts, correcting the supplied validationError. Use validationError.path to locate the affected card or field and validationError.rule to correct that risk category. Rebuild from original intent and confirmed facts, not from rejected wording. Do not neutralize the whole block because one claim failed. Preserve supported ideas by selecting them again from available atomic groundingFacts; exact preservation of old strings is neither possible nor required because the rejected output is absent. For requested advantages blocks, prioritize the confirmed advantages atoms from ConfirmedBusinessFacts: one supported fact per standalone card, 3–6 cards, safe paraphrases preserving subject, scope, conditions, quantities and negation. For UNGROUNDED_PRICE_CLAIM, if a price-related atomic groundingFact is available, reuse that atomic groundingFact verbatim; do not paraphrase the price claim or invent synonyms. Do not combine multiple claims in one point or use a composite originalValue when separate atoms are available. Use neutral useful copy only for an individual card lacking suitable confirmed evidence; do not substitute generic audience, geography or assortment cards for available confirmed strengths. Original requested block type and normalized intent remain binding creative context, never factual authority. Remove the unsupported claim or use neutral wording without a new company promise. Never replace one unsupported quality, service, manufacturing, price or guarantee claim with another unsupported claim. For UNGROUNDED_SERVICE_CLAIM, omit the unsupported service entirely; do not replace it with another invented service. Recheck all schema, security, CTA and grounding rules. The rejected output is intentionally not supplied. All original rules still apply.';
/** Only a first, safely projected grounding rejection permits one new generation. */
export function contentCorrectionMessages(error:unknown,generation:number):AIRequest['messages'] {
 const diagnostic=safeContentValidationError(error);
 return generation===0&&diagnostic?.stage==='content-grounding'
  ?[{role:'system',content:CORRECTION_INSTRUCTIONS},untrustedDataMessage({validationError:diagnostic})]:[];
}
